import { useCallback } from 'react';
import * as Haptics from 'expo-haptics';
import { useAudioPlayer } from 'expo-audio';

import { useSettings } from '@/hooks/use-habits';

// The chime is generated by scripts/generate-chime.js. If the asset is missing,
// the require throws at bundle time, so keep it generated (committed).
const chime = require('@/assets/sounds/chime.wav');

/**
 * The core-loop payoff. `fireReward()` runs the multi-sensory celebration:
 * a success haptic plus a chime (when sound is enabled). The visual burst is
 * driven separately by the caller via <RewardBurst trigger={...} />.
 */
export function useReward() {
  const { soundEnabled } = useSettings();
  const player = useAudioPlayer(chime);

  return useCallback(() => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
    if (soundEnabled) {
      try {
        player.seekTo(0);
        player.play();
      } catch {
        // Audio is best-effort; the haptic + visual still land.
      }
    }
  }, [player, soundEnabled]);
}
